version: "3.8"
#compose file version 3.8
services:
#hizmetlerin tanımlandığı bölüm
  mariadb:
  #mariadb servisi
    container_name: mariadb
    build: ./requirements/mariadb
    #mariadb klasörü içerisindeki Dockerfile dosyasını kullanarak imaj oluşturulur
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    #mariadb servisi otomatik olarak başlatılır
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
      #443 portu dışarıdan erişime açılır
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped

networks:
  inception:
    name: inception
    driver: bridge
    #inception adında bir bridge network oluşturulur

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eozdur/data/wordpress
    #wordpress klasörü /home/eozdur/data/wordpress klasörüne bağlanır
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eozdur/data/mariadb